<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>540d7a7f-242a-411f-b66e-56689f13375b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="NewFolder\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediFormManager.Application\MediFormManager.Application.csproj" />
    <ProjectReference Include="..\MediFormManager.Domain\MediFormManager.Domain.csproj" />
    <ProjectReference Include="..\MediFormManager.Infrastructure\MediFormManager.Infrastructure.csproj" />
  </ItemGroup>

</Project>
